# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jump_to.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JumpToDialog(object):
    def setupUi(self, JumpToDialog):
        JumpToDialog.setObjectName("JumpToDialog")
        JumpToDialog.resize(580, 234)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(JumpToDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.question_comboBox = QtWidgets.QGroupBox(JumpToDialog)
        self.question_comboBox.setObjectName("question_comboBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.question_comboBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.answer_label = QtWidgets.QLabel(self.question_comboBox)
        self.answer_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.answer_label.setIndent(0)
        self.answer_label.setObjectName("answer_label")
        self.verticalLayout.addWidget(self.answer_label)
        self.answer_comboBox = QtWidgets.QComboBox(self.question_comboBox)
        self.answer_comboBox.setObjectName("answer_comboBox")
        self.verticalLayout.addWidget(self.answer_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.jump_label = QtWidgets.QLabel(self.question_comboBox)
        self.jump_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.jump_label.setObjectName("jump_label")
        self.verticalLayout_2.addWidget(self.jump_label)
        self.jump_comboBox = QtWidgets.QComboBox(self.question_comboBox)
        self.jump_comboBox.setObjectName("jump_comboBox")
        self.verticalLayout_2.addWidget(self.jump_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.question_comboBox)
        self.error_label = QtWidgets.QLabel(JumpToDialog)
        self.error_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.error_label.setIndent(-1)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_4.addWidget(self.error_label)
        self.saveAndCancelButtonBox = QtWidgets.QDialogButtonBox(JumpToDialog)
        self.saveAndCancelButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.saveAndCancelButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.saveAndCancelButtonBox.setObjectName("saveAndCancelButtonBox")
        self.verticalLayout_4.addWidget(self.saveAndCancelButtonBox)

        self.retranslateUi(JumpToDialog)
        self.saveAndCancelButtonBox.accepted.connect(JumpToDialog.accept) # type: ignore
        self.saveAndCancelButtonBox.rejected.connect(JumpToDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(JumpToDialog)

    def retranslateUi(self, JumpToDialog):
        _translate = QtCore.QCoreApplication.translate
        JumpToDialog.setWindowTitle(_translate("JumpToDialog", "Jump to"))
        self.question_comboBox.setTitle(_translate("JumpToDialog", "Вопрос"))
        self.answer_label.setText(_translate("JumpToDialog", "Ответ"))
        self.jump_label.setText(_translate("JumpToDialog", "Перепрыгнуть на:"))
        self.error_label.setText(_translate("JumpToDialog", "<html><head/><body><p><br/></p></body></html>"))
