# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_cicrcle.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SetCircleDialog(object):
    def setupUi(self, SetCircleDialog):
        SetCircleDialog.setObjectName("SetCircleDialog")
        SetCircleDialog.resize(580, 144)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(SetCircleDialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.question_comboBox = QtWidgets.QGroupBox(SetCircleDialog)
        self.question_comboBox.setObjectName("question_comboBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.question_comboBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_label = QtWidgets.QLabel(self.question_comboBox)
        self.start_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.start_label.setIndent(0)
        self.start_label.setObjectName("start_label")
        self.verticalLayout.addWidget(self.start_label)
        self.start_comboBox = QtWidgets.QComboBox(self.question_comboBox)
        self.start_comboBox.setObjectName("start_comboBox")
        self.verticalLayout.addWidget(self.start_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.finish_label = QtWidgets.QLabel(self.question_comboBox)
        self.finish_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.finish_label.setObjectName("finish_label")
        self.verticalLayout_2.addWidget(self.finish_label)
        self.finish_comboBox = QtWidgets.QComboBox(self.question_comboBox)
        self.finish_comboBox.setObjectName("finish_comboBox")
        self.verticalLayout_2.addWidget(self.finish_comboBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.question_comboBox)
        self.saveAndCancelButtonBox = QtWidgets.QDialogButtonBox(SetCircleDialog)
        self.saveAndCancelButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.saveAndCancelButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.saveAndCancelButtonBox.setObjectName("saveAndCancelButtonBox")
        self.verticalLayout_4.addWidget(self.saveAndCancelButtonBox)

        self.retranslateUi(SetCircleDialog)
        self.saveAndCancelButtonBox.accepted.connect(SetCircleDialog.accept) # type: ignore
        self.saveAndCancelButtonBox.rejected.connect(SetCircleDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SetCircleDialog)

    def retranslateUi(self, SetCircleDialog):
        _translate = QtCore.QCoreApplication.translate
        SetCircleDialog.setWindowTitle(_translate("SetCircleDialog", "Set circle"))
        self.question_comboBox.setTitle(_translate("SetCircleDialog", "Вопрос"))
        self.start_label.setText(_translate("SetCircleDialog", "Повторять вопросы с:"))
        self.finish_label.setText(_translate("SetCircleDialog", "По:"))
