# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(748, 569)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.new_question_button = QtWidgets.QPushButton(self.centralwidget)
        self.new_question_button.setObjectName("new_question_button")
        self.verticalLayout.addWidget(self.new_question_button)
        self.questions_table = QtWidgets.QTableWidget(self.centralwidget)
        self.questions_table.setColumnCount(5)
        self.questions_table.setObjectName("questions_table")
        self.questions_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.questions_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.questions_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.questions_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.questions_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.questions_table.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.questions_table)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Med"))
        self.new_question_button.setText(_translate("MainWindow", "Новый вопрос"))
        item = self.questions_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "№"))
        item = self.questions_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Вопрос"))
        item = self.questions_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Коротко"))
        item = self.questions_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Переход на"))
        item = self.questions_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Установить переход"))
